// ReSTIR per-frame uniforms, the atlas mapping, seeds and the path-dimension accessor (restir-api.md §2.9, §2.10, §3.2,
// §5 and appendix B.3; math.md#rng-layout [M4 addition]). Mirror of the uniforms: render/restir/layout.ts.
//   G0 binding 4  RestirParams (128 B)          G0 binding 7  RsDispatch (dynamic offset into a 256-B-stride ring)
// ReSTIR G-buffer textures (group 2; §2.5) are declared here by define, so every pass declares them identically:
//   sampled   RS_VBUF_BINDING rsVbuf (u32) · RS_GEO_BINDING rsGeo · RS_L1_BINDING rsL1 · RS_SHADE_BINDING rsShade ·
//             RS_FRAME_BINDING rsFrame · RS_PAIRTEX_BINDING pairTex (texture_2d_array<i32>)
//             M5: RS_VBUF_PREV_BINDING rsVbufPrev · RS_GEO_PREV_BINDING rsGeoPrev (frame t−1, parity 1 − g)
//   storage   RS_VBUF_W_BINDING rsVbufOut · RS_GEO_W_BINDING rsGeoOut · RS_L1_W_BINDING rsL1Out ·
//             RS_SHADE_W_BINDING rsShadeOut · RS_FRAME_W_BINDING rsFrameOut
// Binding defines are generated by render/restir/resources.ts restirPassDefines() as '<n>u' strings, so binding 0 is
// truthy in #if (restir-api.md Changelog A4).
#include "common/frame.wgsl"
#include "common/rng-path.wgsl"
#include "restir/types.wgsl"

struct RestirParams {          // 128 B, G0 binding 4 (layout.ts RESTIR_PARAMS_SIZE)
  atlasSize: vec2u,            //   0
  memberSize: vec2u,           //   8  (= frame.resolution)
  memberCols: u32,             //  16
  memberCount: u32,            //  20  E
  maxBounces: u32,             //  24
  flags: u32,                  //  28  RSF_*
  numTrees: u32,               //  32  S
  numSlots: u32,               //  36  NS
  numRounds: u32,              //  40
  rrMinBounces: u32,           //  44
  tau: f32,                    //  48  2e-4
  alphaMin: f32,               //  52  0.2
  wScale: f32,                 //  56  plant (1 = off)
  crit2022MinDist: f32,        //  60
  pairTexSize: vec4u,          //  64  layers 0..3
  pairTexSize2: vec4u,         //  80  layers 4..7
  lightMode: u32,              //  96  0 = A
  memberBase: u32,             // 100  member id of atlas member 0 (sequential runs of member m; Changelog A5)
  // M5 (restir-temporal-api.md §2.7, appendix B.2; were pad1, pad2, pad3): struct size unchanged (128 B)
  boostSlots: u32,             // 104  NB (0 = off); numSlots = slots + NB
  tMode: u32,                  // 108  TM_*
  cCap: f32,                   // 112  20
  tPlants: u32,                // 116  TP_*
  pad4: u32, pad5: u32,        // 120..127
}
struct RsDispatch {            // 32 B used, 256 B ring stride, G0 binding 7 (hasDynamicOffset)
  t: u32, passId: u32, round: u32, treeBase: u32,
  treeCount: u32, flags: u32, rowBase: u32, rowEnd: u32,
}
@group(0) @binding(4) var<uniform> rsParams: RestirParams;
@group(0) @binding(7) var<uniform> rsDispatch: RsDispatch;

#if RS_VBUF_BINDING
@group(2) @binding($RS_VBUF_BINDING) var rsVbuf: texture_2d<u32>;
fn rs_vbuf(px: vec2u) -> vec4u { return textureLoad(rsVbuf, px, 0); }
#endif
#if RS_GEO_BINDING
@group(2) @binding($RS_GEO_BINDING) var rsGeo: texture_2d<f32>;
fn rs_geo(px: vec2u) -> vec4f { return textureLoad(rsGeo, px, 0); }
#endif
#if RS_L1_BINDING
@group(2) @binding($RS_L1_BINDING) var rsL1: texture_2d<f32>;
#endif
#if RS_SHADE_BINDING
@group(2) @binding($RS_SHADE_BINDING) var rsShade: texture_2d<f32>;
#endif
#if RS_FRAME_BINDING
@group(2) @binding($RS_FRAME_BINDING) var rsFrame: texture_2d<f32>;
#endif
#if RS_PAIRTEX_BINDING
@group(2) @binding($RS_PAIRTEX_BINDING) var pairTex: texture_2d_array<i32>;
#endif
// M5 (restir-temporal-api.md §2.6): the previous frame's ReSTIR G-buffer (parity 1 − g), sampled.
#if RS_VBUF_PREV_BINDING
@group(2) @binding($RS_VBUF_PREV_BINDING) var rsVbufPrev: texture_2d<u32>;
fn rs_vbuf_prev(px: vec2u) -> vec4u { return textureLoad(rsVbufPrev, px, 0); }
#endif
#if RS_GEO_PREV_BINDING
@group(2) @binding($RS_GEO_PREV_BINDING) var rsGeoPrev: texture_2d<f32>;
fn rs_geo_prev(px: vec2u) -> vec4f { return textureLoad(rsGeoPrev, px, 0); }
#endif
#if RS_VBUF_W_BINDING
@group(2) @binding($RS_VBUF_W_BINDING) var rsVbufOut: texture_storage_2d<rgba32uint, write>;
#endif
#if RS_GEO_W_BINDING
@group(2) @binding($RS_GEO_W_BINDING) var rsGeoOut: texture_storage_2d<rgba32float, write>;
#endif
#if RS_L1_W_BINDING
@group(2) @binding($RS_L1_W_BINDING) var rsL1Out: texture_storage_2d<rgba32float, write>;
#endif
#if RS_SHADE_W_BINDING
@group(2) @binding($RS_SHADE_W_BINDING) var rsShadeOut: texture_storage_2d<rgba32float, write>;
#endif
#if RS_FRAME_W_BINDING
@group(2) @binding($RS_FRAME_W_BINDING) var rsFrameOut: texture_storage_2d<rgba32float, write>;
#endif

/// Atlas pixel → (member, member-local pixel). Invalid outside the atlas, outside the dispatch's row band
/// [rowBase, rowEnd) and on inactive members (≥ E).
struct RsPix { valid: bool, member: u32, local: vec2u, localIdx: u32, ai: u32, px: vec2u }

fn rs_pix(px: vec2u) -> RsPix {
  var p: RsPix;
  p.px = px;
  let W = rsParams.memberSize.x;
  let H = rsParams.memberSize.y;
  let mcol = px.x / W;
  let mrow = px.y / H;
  let m = mrow * rsParams.memberCols + mcol;
  p.valid = px.x < rsParams.atlasSize.x && px.y < rsParams.atlasSize.y && px.y >= rsDispatch.rowBase && px.y < rsDispatch.rowEnd
    && mcol < rsParams.memberCols && m < rsParams.memberCount;
  p.member = rsParams.memberBase + m;
  p.local = vec2u(px.x - mcol * W, px.y - mrow * H);
  p.localIdx = p.local.y * W + p.local.x;
  p.ai = px.y * rsParams.atlasSize.x + px.x;
  return p;
}

/// Frame key = tree-0 path seed = the PT's initSeed for the same (runSeed, member, t, pixel) (math.md#rng-layout).
fn rs_frame_key(member: u32, t: u32, localIdx: u32) -> vec2u { return path_init_seed(frame.runSeed, member, t, localIdx); }

/// Path seed of tree s (offline S trees): s = 0 is the key itself.
fn rs_tree_seed(key: vec2u, s: u32) -> vec2u {
  if (s == 0u) { return key; }
  return pcg4d(vec4u(key.x, key.y, s, STREAM_TREE)).xy;
}

/// Sub-pixel jitter: JITTER_IID = rand2(key.x, 0, STREAM_JITTER) (= the PT's for the same member); else frame.jitter.
fn rs_jitter(key: vec2u, px: RsPix) -> vec2f {
  if (frame.jitterMode == JITTER_IID) { return rand2(key.x, 0u, STREAM_JITTER); }
  return frame.jitter;
}

/// Resampling stream of the RESAMPLING pixel's key (streaming RIS, spatial selection).
fn rs_rand(key: vec2u, passId: u32, counter: u32) -> f32 {
  return u32_to_unit(pcg4d(vec4u(key.x, key.y ^ (passId * 0x9e3779b9u), counter, STREAM_RESAMPLE)).x);
}

/// The ONLY path-dimension accessor of the path tree and replay (the dense PSS sweep overrides it: RS_RNG_OVERRIDE,
/// the includer then provides fn rs_rng_override(seed: vec2u, vertex: u32, slot: u32) -> u32).
fn rs_path_hash(seed: vec2u, vertex: u32, slot: u32) -> u32 {
#if RS_RNG_OVERRIDE
  return rs_rng_override(seed, vertex, slot);
#else
  return path_hash(seed, vertex, slot);
#endif
}
fn rs_path_u01(seed: vec2u, vertex: u32, slot: u32) -> f32 { return u32_to_unit(rs_path_hash(seed, vertex, slot)); }
/// (u_lobe, u_h1, u_h2, u_rt) of vertex b.
fn rs_path_bsdf_u4(seed: vec2u, vertex: u32) -> vec4f {
  return vec4f(rs_path_u01(seed, vertex, SLOT_LOBE), rs_path_u01(seed, vertex, SLOT_H1),
               rs_path_u01(seed, vertex, SLOT_H2), rs_path_u01(seed, vertex, SLOT_RT));
}

fn rs_cam_pos() -> vec3f { return frame.cam.camToWorld[3].xyz; }
/// The frame's seed index t: RsDispatch.t, or frame.seedIndex in interactive mode (the renderer owns the frame uniforms).
fn rs_t() -> u32 { return select(rsDispatch.t, frame.seedIndex, (rsParams.flags & RSF_INTERACTIVE) != 0u); }
