// T-E (restir-temporal-api.md §6): the M5 gate configuration and its pure helpers — unit lists of §6.2/§6.3/§6.5, seeds,
// suite FWER units, the sizing rule (per test frame and aggregate incl. masks, R floor, multiples of E, frozen PT), the
// Q4 cap decision, lock chunks, T16 for chains (history resets), the chain runner's host reduction and npz writer, and U-TR-1's
// deterministic parts.
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { ChainFrameCollector, reduceAtlas } from '../../src/core/render/restir/chain-runner.ts';
import { readNpz, writeNpz, type NpzArray } from '../../src/core/render/restir/npz.ts';
import { RESTIR_PRESETS } from '../../src/core/render/restir/presets.ts';
import { SEEDS as M4_SEEDS } from '../../validation/harness/gate-m4.ts';
import {
  DYN_UNITS, E_MEMBERS, M5_AVG_SCENES, M5_DEFERRED_PLANTS, M5_PLANTS, M5_SEQUENCES, M5_STATIC, R_FLOOR, SEEDS, STATIC, UNIT_CAP_RAISED_S, UNIT_CAP_S, U8_SCENES,
  aggFromImages, aggFromNpz, capDecision, chainChunks, globalOnly, nUnits, pkgDir, sizeGroup, t16ChainProblems, uVec,
} from '../../validation/harness/gate-m5.ts';
import { M5_PACKAGES } from '../../validation/scenes/make-m5.ts';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));

describe('unit lists (restir-temporal-api.md §6.2, §6.3, §6.5)', () => {
  it('every package of the gate is generated by make-m5.ts; committed sequence packages carry the gate\'s T and test frames', () => {
    const gen = new Set(M5_PACKAGES());
    for (const p of [...M5_STATIC.map((s) => s.pkg), ...M5_SEQUENCES.map((s) => s.pkg), ...U8_SCENES]) expect(gen.has(p), p).toBe(true);
    for (const s of M5_SEQUENCES) {
      const f = path.join(ROOT, pkgDir(s.pkg), 'scene.json');
      if (!existsSync(f)) { expect(s.env, `${s.pkg} must be committed`).toBe(true); continue; }
      const j = JSON.parse(readFileSync(f, 'utf8'));
      expect(j.sequence, s.pkg).toMatchObject({ fps: 24, frameCount: s.T, testFrames: s.testFrames });
      expect(j.frames.length, s.pkg).toBe(s.T);
      expect(j.frames.map((x: { frame: number }) => x.frame)).toEqual(Array.from({ length: s.T }, (_, i) => i));
    }
  });

  it('8 static scenes (TD28), 3 time-average scenes (Q9), 18 dynamic units (13 + Talbot/E2 x2 (Q11) + boost (Q7)), 20 plants (+ 4 deferred to M6), 6 U8 scenes', () => {
    expect(M5_STATIC).toHaveLength(8);
    expect(M5_AVG_SCENES).toEqual(['m5s_cornell_i', 'm5s_glossy_v1', 'm5s_overcast_rect_b3']);
    expect(DYN_UNITS).toHaveLength(18);
    expect(DYN_UNITS.filter((u) => u.variant === 'base')).toHaveLength(13);
    expect(DYN_UNITS.filter((u) => u.variant !== 'base').map((u) => `${u.pkg}:${u.variant}`).sort()).toEqual([
      'ixs_b_area_256:e2', 'ixs_b_area_256:talbot', 'ixs_d_camera_256:boost', 'ixs_e_addremove_256:e2', 'ixs_e_addremove_256:talbot']);
    expect(M5_PLANTS).toHaveLength(20);
    expect(M5_DEFERRED_PLANTS.map((p) => p.id)).toEqual(['U8-4', 'U8-7', 'U8-8', 'U8-10']);
    expect(M5_PLANTS.some((p) => p.id === 'U8-4')).toBe(false);
    expect(U8_SCENES).toHaveLength(6);
    // every predicted frame is a frame of the plant's package
    for (const p of M5_PLANTS) {
      const s = M5_SEQUENCES.find((x) => x.pkg === p.pkg);
      for (const x of p.predict) expect(x.frame < (s?.T ?? STATIC.T), `${p.id} f${x.frame}`).toBe(true);
    }
    expect(nUnits() % 4).toBe(0);
  });

  it('seeds are disjoint from M4 and from each other; presets follow TD24 (RR off in 3.3–3.6)', () => {
    const v = Object.values(SEEDS);
    expect(new Set(v).size).toBe(v.length);
    for (const s of v) expect(Object.values(M4_SEEDS)).not.toContain(s);
    expect(RESTIR_PRESETS.temporal).toMatchObject({ trees: 1, rounds: 0, rr: false, temporal: true });
    expect(RESTIR_PRESETS.full).toMatchObject({ trees: 1, rounds: 1, slots: 3, diskRadius: 30, rr: false, temporal: true });
  });
});

describe('sizing (PLAN §7.3, §6.4, §6.6)', () => {
  const u = (x: number[]) => Float64Array.from(x);
  it('R is a multiple of E, >= the floor, and grows with the chain variance; PT samples shared over variants', () => {
    const z = sizeGroup([{ frame: 1, u: u([10, 0, 5]), msPerSample: 0.001 }], [
      { id: 'a', u: new Map([[1, u([2000, 0, 1000])]]), msPerChain: 50, rFloor: R_FLOOR },
      { id: 'b', u: new Map([[1, u([10, 0, 10])]]), msPerChain: 50, rFloor: R_FLOOR },
    ]);
    expect(z.chains.a.R % E_MEMBERS).toBe(0);
    expect(z.chains.a.R).toBeGreaterThanOrEqual(2000 * 1.25);
    expect(z.chains.b.R).toBe(R_FLOOR);
    expect(z.pt[1].spp).toBeGreaterThanOrEqual(256);
  });
  it('a frozen PT size is kept and the chains absorb the rest', () => {
    const z = sizeGroup([{ frame: 5, u: u([1000]), msPerSample: 1, fixedSpp: 256 }], [{ id: 'a', u: new Map([[5, u([100])]]), msPerChain: 1, rFloor: 16 }]);
    expect(z.pt[5]).toMatchObject({ spp: 256, fixed: true });
    const NR = (256 * 16) / 1.25;
    expect(z.chains.a.R).toBeGreaterThanOrEqual((100 / (1 - 1000 / NR)) * 1.25 - 1);
  });
  it('aggFromNpz and aggFromImages agree on the same per-replicate images (global, tiles, masks)', () => {
    const W = 64, H = 64, R = 5;
    const imgs = Array.from({ length: R }, (_, r) => Float32Array.from({ length: W * H * 3 }, (_, i) => ((i * 7 + r * 13) % 17) / 17));
    const mask = Uint8Array.from({ length: W * H }, (_, i) => (i % W < 20 ? 1 : 0));
    const a = aggFromImages(imgs, W, H, 32, [mask], 1);
    const col = new ChainFrameCollector();
    const atlas = new Float32Array(R * W * H * 4);
    imgs.forEach((im, m) => { for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) for (let c = 0; c < 3; c++) atlas[4 * (y * R * W + m * W + x) + c] = im[3 * (y * W + x) + c]; });
    col.add(reduceAtlas(atlas, { atlasW: R * W, W, H, E: R, memberCols: R, frame: 1, masks: { names: ['M'], bits: Uint16Array.from(mask) } }), [0, 1, 2, 3, 4], 1);
    const z = readNpz(writeNpz(col.npzArrays() as NpzArray[])) as unknown as Map<string, { shape: number[]; data: unknown }>;
    const b = aggFromNpz(z, 32);
    expect(b.mean.length).toBe(a.mean.length);
    for (let k = 0; k < a.mean.length; k++) { expect(b.mean[k]).toBeCloseTo(a.mean[k], 5); expect(b.sd[k]).toBeCloseTo(a.sd[k], 5); }
    // 128² aggregation from the 64² tiles (enlarged dyn tiles)
    expect(aggFromNpz(z, 128).nTiles).toBe(1);
    const uv = uVec(b, a, { global: 0.002, tile: 0.02, mask: 0.03 });
    const g = globalOnly(uv, b);
    expect(g.filter((x) => x > 0).length).toBeLessThanOrEqual(4);
  });
  it('Q4: tiles enlarge first, the global once raises the cap to 90 min, beyond that infeasible', () => {
    expect(capDecision(100, 10, false).status).toBe('ok');
    expect(capDecision(UNIT_CAP_S + 1, 10, false).status).toBe('enlarge');
    expect(capDecision(UNIT_CAP_S + 1, UNIT_CAP_S + 1, true).status).toBe('raised');
    expect(capDecision(UNIT_CAP_RAISED_S + 1, UNIT_CAP_RAISED_S + 1, true).status).toBe('infeasible');
  });
  it('lock chunks are whole batches and sum to R/E (chains never split, TD25)', () => {
    for (const [R, s] of [[256, 100], [4096, 3000], [1024, 10_000]] as const) {
      const c = chainChunks(R, 16, s);
      expect(c.reduce((a, b) => a + b, 0)).toBe(R / 16);
      if (s > 12 * 60) expect(Math.max(...c) * 16 * (s / R)).toBeLessThanOrEqual(12 * 60 + 1e-6);
    }
  });
});

describe('T16 for chains (§6.4, TD19)', () => {
  const pt = { ok: true, errors: [], width: 256, height: 256, config: { jitter: 'iid-per-run', maxBounces: 3, lightMode: 'A', rr: false, scene: 'S', env: 'none', frame: 8 } };
  const cm = (o: Record<string, any> = {}) => ({
    kernel: 'restir', kind: 'chains', ok: true, errors: [], width: 256, height: 256, members: 16, config: { scene: 'S', env: 'none' },
    t16: { validationModeUnbiased: true, plantsNamed: [], internalScale: 1, denoiser: 'none', upscaler: 'none', readback: 'linear rsFrame', jitterMode: 'iid-per-run',
      maxBounces: 3, lightMode: 'A', rr: false, temporal: true, cCap: 20, spatialRoundsExecuted: 1, historyPattern: [false, true, true], resetFrames: [0], ...o },
  });
  it('a correct run passes', () => expect(t16ChainProblems(cm(), pt, { rounds: 1, frame: 8 })).toEqual([]));
  it('history must be valid except at the reset frames ("any config change resets history")', () => {
    expect(t16ChainProblems(cm({ historyPattern: [false, false, true] }), pt, { rounds: 1, frame: 8 }).join()).toMatch(/frame 1: history invalid/);
    expect(t16ChainProblems(cm({ historyPattern: [false, true, true], resetFrames: [0, 2] }), pt, { rounds: 1, frame: 8 }).join()).toMatch(/frame 2: history valid/);
  });
  it('RR, cCap, rounds, PT frame and plants are asserted', () => {
    expect(t16ChainProblems(cm({ rr: true }), pt, { rounds: 1, frame: 8 }).join()).toMatch(/RR/);
    expect(t16ChainProblems(cm({ cCap: 21 }), pt, { rounds: 1, frame: 8 }).join()).toMatch(/cCap/);
    expect(t16ChainProblems(cm({ spatialRoundsExecuted: 0 }), pt, { rounds: 1, frame: 8 }).join()).toMatch(/spatial rounds/);
    expect(t16ChainProblems(cm(), pt, { rounds: 1, frame: 9 }).join()).toMatch(/PT reference frame/);
    expect(t16ChainProblems(cm({ validationModeUnbiased: false }), pt, { rounds: 1, frame: 8 }).join()).toMatch(/unbiased/);
    expect(t16ChainProblems(cm({ validationModeUnbiased: false, plantsNamed: ['n1Mixed'] }), pt, { plant: true, rounds: 1, frame: 8 })).toEqual([]);
  });
});

describe('chain host reduction (chain-runner.ts)', () => {
  it('reduceAtlas: tile / global / mask sums and pixel moments equal a brute-force f64 reduction', () => {
    const W = 40, H = 24, E = 3, cols = 2, atlasW = cols * W, atlasH = 2 * H;
    const img = Float32Array.from({ length: atlasW * atlasH * 4 }, (_, i) => ((i * 2654435761) % 1000) / 1000);
    const bits = Uint16Array.from({ length: W * H }, (_, i) => (i % 3 === 0 ? 1 : 0) | (i % 5 === 0 ? 2 : 0));
    const r = reduceAtlas(img, { atlasW, W, H, E, memberCols: cols, frame: 3, masks: { names: ['a', 'b'], bits } });
    for (let m = 0; m < E; m++) {
      const ox = (m % cols) * W, oy = Math.floor(m / cols) * H;
      let g = 0, t16 = 0, ma = 0, mb = 0;
      for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
        const v = img[4 * ((oy + y) * atlasW + ox + x) + 1];
        g += v;
        if (y >= 16 && x >= 32) t16 += v;
        if (bits[y * W + x] & 1) ma += v;
        if (bits[y * W + x] & 2) mb += v;
      }
      expect(r.global[3 * m + 1]).toBeCloseTo(g, 6);
      const th = Math.ceil(H / 16), tw = Math.ceil(W / 16);
      expect(r.tiles[16].data[3 * ((m * th + 1) * tw + 2) + 1]).toBeCloseTo(t16, 6);
      expect(r.masks[3 * (m * 2 + 0) + 1]).toBeCloseTo(ma, 6);
      expect(r.masks[3 * (m * 2 + 1) + 1]).toBeCloseTo(mb, 6);
    }
    expect(r.maskPixels).toEqual([bits.filter((b) => b & 1).length, bits.filter((b) => b & 2).length]);
    let s = 0;
    for (let m = 0; m < E; m++) s += img[4 * ((Math.floor(m / cols) * H) * atlasW + (m % cols) * W)];
    expect(r.pixelSum[0]).toBeCloseTo(s, 6);
  });
  it('the collector concatenates batches in order and labels rows by chain id (U-TR-1: rows are a function of the chains only)', () => {
    const c = new ChainFrameCollector();
    const W = 16, H = 16;
    for (let b = 0; b < 2; b++) {
      const img = new Float32Array(2 * W * H * 4).fill(b + 1);
      c.add(reduceAtlas(img, { atlasW: 2 * W, W, H, E: 2, memberCols: 2, frame: 1 }), [2 * b, 2 * b + 1], 7002);
    }
    expect(c.seeds).toEqual(['7002:c0', '7002:c1', '7002:c2', '7002:c3']);
    const z = readNpz(writeNpz(c.npzArrays() as NpzArray[]));
    expect(z.get('global')!.shape).toEqual([4, 3]);
    expect(Array.from((z.get('global')!.data as Float64Array)).filter((_, i) => i % 3 === 0)).toEqual([256, 256, 512, 512]);
  });
});
