// M5 scene packages (restir-temporal-api.md §6.2, TD27, TD28, TD30; PLAN §5 M5 exit, §7.1 rungs 3.3–3.6). OWNER T-E.
//   npx tsx validation/scenes/make-m5.ts [outDir] [--only name,name]
// Default output: packages without an environment go to validation/scenes (committed); packages with an HDRI env go to
// validation/out/m5/scenes (gitignored: they embed the downloaded Poly Haven texels, as make-m3c.ts). With an explicit
// outDir every package goes there (the Gate-0 determinism check runs this twice and compares bytes).
//
// Three families:
//  m5s_*  static subset for rungs 3.3–3.5 at 256² (TD28): the M4 packages with render 256² (scene.json render size and
//         name changed, every other byte identical; the env ones are regenerated by make-m3c.ts first).
//  ixs_*  sequence packages for rung 3.6 and the temporal plants (TD27): DENSE frames 0…T−1 (every frame's camera,
//         light matrix/power/size/enabled, env rotation/strength/tint/map), a `sequence {fps, frameCount, testFrames,
//         notes}` block; Mode A, maxBounces 3, 256². Geometry and emissive triangles are static (R17): only the camera,
//         the analytic lights and the env change. Frame k is the state at t = k/24 s, evaluated in closed form here.
//  u8_*   the U8 ladder (TD30): C0c point / C0d spot / C0e rect at 256², b = 0 (pure DI, case (a)) and b = 1 with a
//         diffuse side wall (cases (b), (c), (e)).
// Deterministic: re-running writes byte-identical packages (Gate 0).
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import path from 'node:path';
import { decodeHdr } from '../../src/core/scene/env/hdr.ts';
import { exportScenePackage, type PackageFrame, type PackageLightOverride, type PackageSequence } from '../../src/core/scene/scene-package.ts';
import type { EnvironmentData, LightData, MaterialData, SceneData } from '../../src/core/scene/types.ts';
import { MeshBuilder, ROOT, cornellBase, deg, light, lightToward, lookAt, norm, resetLightIds, sceneOf, v1, type V3 } from './scene-kit.ts';

const argv = process.argv.slice(2);
const flag = (k: string) => { const i = argv.indexOf(k); return i >= 0 ? argv[i + 1] : undefined; };
const ONLY = flag('--only') ? new Set(flag('--only')!.split(',')) : undefined;
const EXPLICIT = argv[0] && !argv[0].startsWith('--') ? path.resolve(argv[0]) : undefined;
const OUT_STATIC = EXPLICIT ?? path.join(ROOT, 'validation/scenes');
const OUT_ENV = EXPLICIT ?? path.join(ROOT, 'validation/out/m5/scenes');
const HDRI_DIR = path.join(ROOT, 'validation/assets/downloaded/hdri');
const SRC = (what: string) => ({ uri: `validation/scenes/make-m5.ts (${what})` });
export const FPS = 24;

type Gen = () => Promise<void>;
const gens: [string, Gen][] = [];
const def = (name: string, g: Gen) => gens.push([name, g]);

// ---- small math -------------------------------------------------------------------------------------------------------

const lerp = (a: number, b: number, u: number) => a + (b - a) * u;
const lerp3 = (a: readonly number[], b: readonly number[], u: number): V3 => [lerp(a[0], b[0], u), lerp(a[1], b[1], u), lerp(a[2], b[2], u)];
const clamp01 = (x: number) => Math.min(1, Math.max(0, x));
/** Rotation about +Y by θ applied to a direction. */
const rotYv = (v: readonly number[], th: number): V3 => [Math.cos(th) * v[0] + Math.sin(th) * v[2], v[1], -Math.sin(th) * v[0] + Math.cos(th) * v[2]];
/** R_y(θ)·M (rotation part), translation replaced by p. */
function rotYMatrix(m: ArrayLike<number>, th: number, p: readonly number[]): number[] {
  const X = rotYv([m[0], m[1], m[2]], th), Y = rotYv([m[4], m[5], m[6]], th), Z = rotYv([m[8], m[9], m[10]], th);
  return [...X, 0, ...Y, 0, ...Z, 0, p[0], p[1], p[2], 1];
}
const pointM = (p: readonly number[]) => [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, p[0], p[1], p[2], 1];
/** Piecewise-linear key interpolation over frame numbers (holds before the first / after the last key). */
function keyed(keys: [number, V3][], k: number): V3 {
  if (k <= keys[0][0]) return [...keys[0][1]] as V3;
  for (let i = 1; i < keys.length; i++) if (k <= keys[i][0]) return lerp3(keys[i - 1][1], keys[i][1], (k - keys[i - 1][0]) / (keys[i][0] - keys[i - 1][0]));
  return [...keys[keys.length - 1][1]] as V3;
}
const range = (n: number) => Array.from({ length: n }, (_, i) => i);

// ---- package writer -------------------------------------------------------------------------------------------------------

interface SeqOpts {
  camera: { matrix: number[]; yfov: number };
  maxBounces?: number;
  T: number;
  testFrames: number[];
  notes: string;
  frame: (k: number) => Omit<PackageFrame, 'frame'>;
  envMaps?: { id: string; env: EnvironmentData }[];
  extra?: Record<string, unknown>;
}

async function writePkg(dir: string, scene: SceneData, o: Parameters<typeof exportScenePackage>[1], extra?: Record<string, unknown>): Promise<void> {
  const pkg = await exportScenePackage(scene, o);
  if (extra) pkg.files.set('scene.json', new TextEncoder().encode(JSON.stringify({ ...pkg.json, ...extra }, null, 1)));
  rmSync(dir, { recursive: true, force: true });
  mkdirSync(dir, { recursive: true });
  for (const [k, b] of pkg.files) writeFileSync(path.join(dir, k), b);
}

async function writeSequence(name: string, scene: SceneData, o: SeqOpts): Promise<void> {
  if (o.testFrames.some((t) => !(Number.isInteger(t) && t >= 0 && t < o.T))) throw new Error(`${name}: test frame outside 0..${o.T - 1}`);
  const frames: PackageFrame[] = range(o.T).map((k) => ({ frame: k, ...o.frame(k) }));
  const sequence: PackageSequence = { fps: FPS, frameCount: o.T, testFrames: o.testFrames, notes: o.notes };
  const out = scene.env ? OUT_ENV : OUT_STATIC;
  await writePkg(path.join(out, name), scene, {
    camera: o.camera, render: { width: 256, height: 256, maxBounces: o.maxBounces ?? 3 }, lightMode: 'A', flatShaded: true, name,
    frames, sequence, ...(o.envMaps ? { envMaps: o.envMaps } : {}), source: SRC(o.notes),
  }, { tier: 'tight', ...o.extra });
}

// ---- shared scene pieces ----------------------------------------------------------------------------------------------------

type Cornell = Awaited<ReturnType<typeof cornellBase>>;
const matIndex = (mats: readonly MaterialData[], name: string) => {
  const i = mats.findIndex((m) => m.name === name);
  if (i < 0) throw new Error(`material ${name} missing`);
  return i;
};

/** The Cornell box (+ an optional occluder box on the floor, + an optional GGX floor material). */
function cornellWith(c: Cornell, o: { box?: boolean; ggxFloor?: number; open?: boolean } = {}): { mb: MeshBuilder; mats: MaterialData[] } {
  const g = c.geometry;
  const mats = [...c.materials];
  const white = matIndex(mats, 'white');
  let floorMat = white;
  if (o.ggxFloor !== undefined) {
    mats.push(v1('floor_ggx', { diffuse: [0.6, 0.6, 0.6], glossy: [0.8, 0.8, 0.8], roughness: o.ggxFloor, mix: 0.5 }));
    floorMat = mats.length - 1;
  }
  let ymax = -Infinity;
  for (let i = 1; i < g.positions.length; i += 3) ymax = Math.max(ymax, g.positions[i]);
  const mb = new MeshBuilder();
  for (let t = 0; t < g.indices.length / 3; t++) {
    const P = (k: number): V3 => { const i = g.indices[3 * t + k]; return [g.positions[3 * i], g.positions[3 * i + 1], g.positions[3 * i + 2]]; };
    const ys = [0, 1, 2].map((k) => P(k)[1]);
    if (o.open && ys.every((y) => Math.abs(y - ymax) < 1e-6)) continue;            // open to the sky: drop the ceiling
    const isFloor = ys.every((y) => Math.abs(y) < 1e-6);
    mb.tri(P(0), P(1), P(2), isFloor ? floorMat : g.triMaterial[t]);
  }
  // occluder: a white box standing on the floor slightly behind the centre (shadows, disocclusions)
  if (o.box) mb.box([-0.02, 0, -0.16], [0.10, 0.20, -0.04], white, { rotY: 12 * deg, omit: ['-y'] });
  return { mb, mats };
}

const envBase = { strength: 1, tint: [1, 1, 1] as V3, rotationZ: 0, visibleToCamera: true };
const hdriCache = new Map<string, EnvironmentData>();
function hdri(id: string, rotationZ = 0): EnvironmentData {
  let e = hdriCache.get(id);
  if (!e) {
    const file = path.join(HDRI_DIR, `${id}_1k.hdr`);
    let bytes: Uint8Array;
    try { bytes = new Uint8Array(readFileSync(file)); } catch { throw new Error(`${file} missing: run npx tsx validation/assets/fetch_hdris.ts`); }
    const img = decodeHdr(bytes);
    e = { ...envBase, name: `${id}_1k`, width: img.width, height: img.height, texels: img.texels };
    hdriCache.set(id, e);
  }
  return { ...e, rotationZ };
}
/** A different map for the ixs_k swap: the same HDRI box-filtered 2× (half resolution; a different texture and
 *  importance table, tight tier). */
function halfRes(e: EnvironmentData): EnvironmentData {
  const W = e.width / 2, H = e.height / 2;
  const t = new Float32Array(W * H * 4);
  for (let y = 0; y < H; y++) for (let x = 0; x < W; x++) {
    for (let c = 0; c < 3; c++) {
      let s = 0;
      for (const [dx, dy] of [[0, 0], [1, 0], [0, 1], [1, 1]]) s += e.texels[4 * ((2 * y + dy) * e.width + 2 * x + dx) + c];
      t[4 * (y * W + x) + c] = Math.fround(s / 4);
    }
    t[4 * (y * W + x) + 3] = 1;
  }
  return { ...e, name: `${e.name}_half`, width: W, height: H, texels: t };
}

const OVERCAST = 'overcast_soil_puresky';
const OVERCAST_GAMMA = 0.9;   // (xiv) overcast γ (make-m3c.ts)

const cornellCam = (c: Cornell) => ({ matrix: [...c.camera.matrix], yfov: c.camera.yfov });
const CAM_TARGET: V3 = [0, 0.18, -0.1];
/** ixs_d fly path (positions at frames 0, 24, 40, 64; looks at the occluder box). */
const FLY: [number, V3][] = [[0, [0, 0.273, 1.0775]], [24, [0.18, 0.36, 0.8]], [40, [-0.12, 0.2, 0.7]], [64, [0.05, 0.3, 0.95]]];
const flyCam = (k: number, yfov: number) => ({ matrix: lookAt(keyed(FLY, k), CAM_TARGET), yfov });

// ---- m5s: static subset at 256² (TD28) -----------------------------------------------------------------------------------

export const M5S: { name: string; src: string; env: boolean }[] = [
  { name: 'm5s_cornell_i', src: 'cornell_i_512', env: false },
  { name: 'm5s_spot_grazing', src: 'iii_spot_grazing_512', env: false },
  { name: 'm5s_glossy_v1', src: 'v_glossy_v1_512', env: false },
  { name: 'm5s_glass_mirror_A', src: 'vi_glass_mirror_A_512', env: false },
  { name: 'm5s_many_lights', src: 'x_many_lights_512', env: false },
  { name: 'm5s_alpha_foliage', src: 'xii_alpha_foliage_512', env: false },
  { name: 'm5s_c0q_openbox_b13', src: 'c0q_openbox_b13_256', env: true },
  { name: 'm5s_overcast_rect_b3', src: 'xiv_overcast_rect_b3_512', env: true },
];

/** Copy a package and set render 256² + name (every other byte identical). */
function resizePackage(srcDir: string, dst: string, name: string, srcName: string): void {
  if (!existsSync(path.join(srcDir, 'scene.json'))) throw new Error(`${srcDir}: missing package`);
  rmSync(dst, { recursive: true, force: true });
  mkdirSync(dst, { recursive: true });
  for (const f of readdirSync(srcDir).sort()) if (f !== 'scene.json') cpSync(path.join(srcDir, f), path.join(dst, f));
  const json = JSON.parse(readFileSync(path.join(srcDir, 'scene.json'), 'utf8')) as Record<string, any>;
  const out = { ...json, name, render: { ...json.render, width: 256, height: 256 }, m5: { derivedFrom: srcName, change: 'render 256x256 (restir-temporal-api.md TD28)', generator: 'validation/scenes/make-m5.ts' } };
  writeFileSync(path.join(dst, 'scene.json'), JSON.stringify(out, null, 1));
}

let m3cDir: string | undefined;
/** make-m3c.ts output for the env sources (generated once per make-m5 run into a scratch dir). */
function m3cSource(name: string): string {
  if (!m3cDir) {
    m3cDir = path.join(OUT_ENV, '.m3c-src');
    const want = M5S.filter((s) => s.env).map((s) => s.src).join(',');
    const r = spawnSync('npx', ['tsx', 'validation/scenes/make-m3c.ts', m3cDir, '--only', want], { cwd: ROOT, encoding: 'utf8' });
    if (r.status !== 0) throw new Error(`make-m3c.ts failed: ${r.stdout}${r.stderr}`);
  }
  return path.join(m3cDir, name);
}

for (const s of M5S) {
  def(s.name, async () => {
    const src = s.env ? m3cSource(s.src) : path.join(ROOT, 'validation/scenes', s.src);
    resizePackage(src, path.join(s.env ? OUT_ENV : OUT_STATIC, s.name), s.name, s.src);
  });
}

// ---- ixs: sequences (TD27, §6.2) -----------------------------------------------------------------------------------------------

def('ixs_a_point_256', async () => {
  resetLightIds();
  // Open scene (no walls, no env, ρ 0.3): the indirect light in the box's shadow stays far below 1 % of the image mean,
  // so cells swept by the shadow edge go from dark to lit (M_new) / lit to dark (M_gone) between frames (dyn_masks.py
  // thresholds 1 % / 5 %). In the Cornell box the indirect light never lets a region drop below 1 % (Changelog E-13).
  const mats = [v1('floor', { diffuse: [0.3, 0.3, 0.3] }), v1('box', { diffuse: [0.3, 0.3, 0.3] })];
  const mb = new MeshBuilder().floor(-2, 2, -2, 2, 0, 0).box([0.1, 0, -0.15], [0.45, 0.4, 0.15], 1, { omit: ['-y'] });
  const L = light('point', new Float32Array(pointM([-1.2, 0.5, -0.6])), 20, { color: [1, 0.9, 0.8] });
  // linear path x −1.2 → +1.2 (6 cm/frame) behind the box (seen from the camera at +z): behind it during frames ≈ 22–28;
  // static after 40. The shadow edge on the floor moves ≈ 3–15 px/frame (near → far from the box).
  const pos = (k: number): V3 => [lerp(-1.2, 1.2, clamp01(k / 40)), 0.5, -0.6];
  await writeSequence('ixs_a_point_256', sceneOf('ixs_a_point_256', mb, mats, [L]), {
    camera: { matrix: lookAt([0.2, 2.0, 2.2], [0.2, 0, -0.2]), yfov: 45 * deg }, T: 81, testFrames: [1, 10, 25, 40, 80],
    notes: 'ixs-a: point light on a linear path behind an occluder box (frames ~22-28), stops at 40; open low-albedo floor',
    frame: (k) => ({ lights: { [L.id]: { matrix: pointM(pos(k)), power: 20 } } }),
  });
});

def('ixs_b_area_256', async () => {
  resetLightIds();
  const c = await cornellBase();
  const { mb, mats } = cornellWith(c, { box: true });
  const s0 = c.rect;
  const L = light('rect', s0.matrix, 4, { sizeX: s0.sizeX, sizeY: s0.sizeY });
  const a = Math.sqrt(1.5);
  await writeSequence('ixs_b_area_256', sceneOf('ixs_b_area_256', mb, mats, [L]), {
    camera: cornellCam(c), T: 41, testFrames: [15, 16, 17, 24, 25, 40],
    notes: 'ixs-b: rect light translating in x and spinning 5 deg/frame about its (downward) normal; area x1.5 from frame 16; power x2 from frame 24',
    frame: (k) => {
      const ov: PackageLightOverride = {
        matrix: rotYMatrix(s0.matrix, 5 * deg * k, [lerp(-0.1, 0.1, k / 40), 0.5, -0.02]),
        power: k >= 24 ? 8 : 4, sizeX: k >= 16 ? s0.sizeX * a : s0.sizeX, sizeY: k >= 16 ? s0.sizeY * a : s0.sizeY,
      };
      return { lights: { [L.id]: ov } };
    },
  });
});

for (const [suffix, blend] of [['b0', 0], ['b03', 0.3]] as const) {
  def(`ixs_c_spot_${suffix}_256`, async () => {
    resetLightIds();
    const c = await cornellBase();
    const { mb, mats } = cornellWith(c, { box: true });
    const p: V3 = [0, 0.5, 0.1], d0 = norm([0.55, -1, -0.35]);
    const L = light('spot', lightToward(d0, p), 6, { spotSize: 45 * deg, spotBlend: blend, color: [1, 0.95, 0.9] });
    const name = `ixs_c_spot_${suffix}_256`;
    await writeSequence(name, sceneOf(name, mb, mats, [L]), {
      camera: cornellCam(c), T: 41, testFrames: [5, 20, 40],
      notes: `ixs-c: spot (45 deg, blend ${blend}) rotating 2 deg/frame about the vertical axis`,
      frame: (k) => ({ lights: { [L.id]: { matrix: Array.from(lightToward(rotYv(d0, 2 * deg * k), p)), power: 6 } } }),
    });
  });
}

function defCamera(name: string, T: number, testFrames: number[], notes: string, o: { ggx?: number; still?: boolean }): void {
  def(name, async () => {
    resetLightIds();
    const c = await cornellBase();
    const { mb, mats } = cornellWith(c, { box: true, ggxFloor: o.ggx });
    const L = light('rect', c.rect.matrix, 4, { sizeX: c.rect.sizeX, sizeY: c.rect.sizeY });
    await writeSequence(name, sceneOf(name, mb, mats, [L]), {
      camera: o.still ? cornellCam(c) : flyCam(0, c.camera.yfov), T, testFrames, notes,
      frame: (k) => (o.still ? {} : { camera: flyCam(k, c.camera.yfov) }),
    });
  });
}
defCamera('ixs_d_camera_256', 65, [8, 16, 24, 32, 40, 48, 56, 64], 'ixs-d: scripted camera fly path around an occluder box (static rect light)', {});
defCamera('ixs_d0_jitter_256', 65, [8, 32, 64], 'ixs-d0: static camera and lights (jitter only)', { still: true });
defCamera('ixs_d_glossy_256', 33, [8, 16, 32], 'ixs-d-glossy: the ixs-d fly path with a GGX r = 0.3 floor (N6)', { ggx: 0.3 });

function defAddRemove(name: string, T: number, testFrames: number[], aScale: number): void {
  def(name, async () => {
    resetLightIds();
    const c = await cornellBase();
    const { mb, mats } = cornellWith(c, { box: true });
    // A (point, low near the red wall) and B (rect, ceiling right) at equal power (1:1); C (spot toward the back-right
    // corner) added at frame 8; A × aScale at 14; B removed at 20. Each light dominates its own region (M_light:<id>).
    const pA: V3 = [-0.2, 0.12, 0.0];
    const A = light('point', new Float32Array(pointM(pA)), 3, { color: [1, 0.8, 0.6] });
    const bM = rotYMatrix(c.rect.matrix, 0, [0.14, 0.53, -0.08]);
    const B = light('rect', new Float32Array(bM), 3, { sizeX: c.rect.sizeX, sizeY: c.rect.sizeY });
    // C points up at the back half of the ceiling (≈ 20 cm away, cone 90°), which A (near the floor) and B (facing down)
    // barely light: M_light:C
    const pC: V3 = [-0.05, 0.35, 0.1], dC = norm([-0.2, 1, -0.5]);
    const C = light('spot', lightToward(dC, pC), 6, { spotSize: 90 * deg, spotBlend: 0.2, color: [0.7, 0.85, 1] });
    await writeSequence(name, sceneOf(name, mb, mats, [A, B, C]), {
      camera: cornellCam(c), T, testFrames,
      notes: `ixs-e: A point + B rect at 1:1; C spot added at 8; A x${aScale} at 14; B removed at 20 (true add/remove: enabled flags)`,
      frame: (k) => ({
        lights: {
          [A.id]: { matrix: pointM(pA), power: k >= 14 ? 3 * aScale : 3 },
          [B.id]: { matrix: bM, power: 3, enabled: k < 20 },
          [C.id]: { matrix: Array.from(C.matrix), power: 6, enabled: k >= 8 },
        },
      }),
      extra: { lightNames: { A: A.id, B: B.id, C: C.id } },
    });
  });
}
defAddRemove('ixs_e_addremove_256', 41, [8, 9, 14, 15, 20, 21, 40], 2);
defAddRemove('ixs_e_half_256', 22, [14, 15, 21], 0.5);

def('ixs_f_combined_256', async () => {
  resetLightIds();
  const c = await cornellBase();
  const { mb, mats } = cornellWith(c, { box: true });
  const P = light('point', new Float32Array(pointM([0.1, 0.45, -0.1])), 2, { color: [1, 0.85, 0.7] });
  const R = light('rect', c.rect.matrix, 3, { sizeX: c.rect.sizeX, sizeY: c.rect.sizeY });
  const front: V3 = [0, 0.273, 1.0775], side: V3 = [0.2, 0.4, 0.6];
  const fov = (k: number) => (k <= 32 ? 30 * deg : lerp(30 * deg, 60 * deg, clamp01((k - 32) / 16)));
  await writeSequence('ixs_f_combined_256', sceneOf('ixs_f_combined_256', mb, mats, [P, R]), {
    camera: { matrix: lookAt(front, CAM_TARGET), yfov: 30 * deg }, T: 49, testFrames: [8, 24, 25, 40, 48],
    notes: 'ixs-f: moving point light + rect power ramp 3 -> 1 W, camera teleport at 24, FOV ramp 30 -> 60 deg over 32-48',
    frame: (k) => ({
      camera: { matrix: lookAt(k < 24 ? front : side, CAM_TARGET), yfov: fov(k) },
      lights: { [P.id]: { matrix: pointM(lerp3([0.1, 0.45, -0.1], [-0.15, 0.3, 0.12], k / 48)), power: 2 }, [R.id]: { matrix: Array.from(R.matrix), power: lerp(3, 1, k / 48) } },
    }),
  });
});

def('ixs_g_sun_256', async () => {
  resetLightIds();
  const mats = [v1('ground', { diffuse: [0.5, 0.5, 0.45] }), v1('wall', { diffuse: [0.7, 0.6, 0.5] }), v1('box', { diffuse: [0.3, 0.45, 0.65] })];
  const mb = new MeshBuilder().floor(-3, 3, -3, 3, 0, 0)
    .quad([-3, 0, -2], [3, 0, -2], [3, 1.5, -2], [-3, 1.5, -2], 1)
    .box([-1.2, 0, -1.2], [-0.4, 0.8, -0.4], 2, { rotY: 10 * deg, omit: ['-y'] })
    .box([0.5, 0, -0.5], [1.1, 0.4, 0.1], 2, { rotY: -25 * deg, omit: ['-y'] });
  const toSun0: V3 = [Math.cos(35 * deg) * Math.cos(20 * deg), Math.sin(35 * deg), Math.cos(35 * deg) * Math.sin(20 * deg)];
  const S = light('sun', lightToward([-toSun0[0], -toSun0[1], -toSun0[2]], [0, 5, 0]), 3, { color: [1, 0.95, 0.85] });
  await writeSequence('ixs_g_sun_256', sceneOf('ixs_g_sun_256', mb, mats, [S]), {
    camera: { matrix: lookAt([0.5, 2.6, 3.6], [0, 0.3, -0.6]), yfov: 50 * deg }, T: 49, testFrames: [8, 24, 48],
    notes: 'ixs-g: courtyard, sun rotating 2 deg/frame about the vertical axis',
    frame: (k) => ({ lights: { [S.id]: { matrix: Array.from(lightToward(rotYv([-toSun0[0], -toSun0[1], -toSun0[2]], -2 * deg * k), [0, 5, 0])), power: 3 } } }),
  });
});

def('ixs_n4_twolights_256', async () => {
  resetLightIds();
  const c = await cornellBase();
  const { mb, mats } = cornellWith(c, { ggxFloor: 0.5 });
  // two equal-power points; B is 3× as far from the floor as A (irradiance ratio 9 below each); rough floor ⇒ most
  // selected paths are deep NEE (class D-NEE); a third dim light moves 1 mm/frame so every frame is a refresh frame
  const A = light('point', new Float32Array(pointM([-0.12, 0.15, -0.1])), 1, { color: [1, 0.9, 0.8] });
  const B = light('point', new Float32Array(pointM([0.12, 0.45, -0.1])), 1, { color: [0.8, 0.9, 1] });
  const C = light('point', new Float32Array(pointM([0, 0.5, 0.25])), 0.2);
  await writeSequence('ixs_n4_twolights_256', sceneOf('ixs_n4_twolights_256', mb, mats, [A, B, C]), {
    camera: cornellCam(c), T: 17, testFrames: [8, 16],
    notes: 'ixs-n4: two equal-power point lights at heights 0.15 / 0.45 (ratio 3), rough GGX floor, a third dim light moving 1 mm/frame (refresh every frame)',
    frame: (k) => ({ lights: { [A.id]: { matrix: pointM([-0.12, 0.15, -0.1]), power: 1 }, [B.id]: { matrix: pointM([0.12, 0.45, -0.1]), power: 1 }, [C.id]: { matrix: pointM([0.001 * k, 0.5, 0.25]), power: 0.2 } } }),
    extra: { lightNames: { A: A.id, B: B.id, C: C.id } },
  });
});

// ---- env sequences (validation/out/m5/scenes) --------------------------------------------------------------------------------------

/** glTF world direction of env texture coordinate (u, v) at rotation γ (math.md#env-mapping envDir; make-m3c.ts). */
function envDirAt(u: number, v: number, g: number): V3 {
  const phi = -2 * Math.PI * u + Math.PI, theta = -Math.PI * v + Math.PI;
  const b = [Math.sin(theta) * Math.cos(phi), Math.sin(theta) * Math.sin(phi), Math.cos(theta)];
  const cg = Math.cos(g), sg = Math.sin(g);
  return [cg * b[0] + sg * b[1], b[2], -(-sg * b[0] + cg * b[1])];
}

/** Synthetic env for ixs-h (dynamic range 10⁶ ≈ 20 EV, a 2.8° patch; the pilots size its variance): sky 0.0002,
 *  ground 0.0001 (dark shadows), a 4×4-texel patch of 100 at elevation ≈ 25° in the direction −z at γ = 0 (behind the objects as seen from the
 *  camera). A 1°/frame rotation then moves the long, sharp shadow of a 1.6 m pole several pixels per frame (M_edge /
 *  cells; with the overcast map no 4×4 cell changed by 25 % between frames, Changelog E-13). */
function windowEnv(): EnvironmentData {
  const W = 512, H = 256, t = new Float32Array(W * H * 4);
  for (let r = 0; r < H; r++) for (let c = 0; c < W; c++) { const v = r >= H / 2 ? 0.0002 : 0.0001; t.set([v, v, v, 1], 4 * (r * W + c)); }
  const row = Math.round((0.5 + 25 / 180) * H);
  let bestU = 0, best = -Infinity;
  for (let c = 0; c < W; c++) { const d = envDirAt((c + 0.5) / W, (row + 0.5) / H, 0); const sc = -d[2] / Math.hypot(d[0], d[2]); if (sc > best) { best = sc; bestU = c; } }
  for (let r = row - 2; r < row + 2; r++) for (let c = bestU - 2; c < bestU + 2; c++) t.set([100, 100, 100, 1], 4 * (r * W + ((c + W) % W)));
  return { ...envBase, name: 'patch-512x256', width: W, height: H, texels: t };
}

def('ixs_h_envrot_256', async () => {
  resetLightIds();
  const mats = [v1('ground', { diffuse: [0.5, 0.5, 0.5] }), v1('lambert', { diffuse: [0.8, 0.8, 0.8] }), v1('ggx', { diffuse: [0, 0, 0], glossy: [0.9, 0.9, 0.9], roughness: 0.3, mix: 1 }), v1('pole', { diffuse: [0.6, 0.5, 0.4] })];
  const mb = new MeshBuilder().floor(-3, 3, -3, 3, 0, 0)
    .icosphere([-0.5, 0.4, 0], 0.4, 3, 1).icosphere([0.5, 0.4, 0], 0.4, 3, 2)
    .box([-0.03, 0, -0.63], [0.03, 1.6, -0.57], 3, { omit: ['-y'] });
  const scene = { ...sceneOf('ixs_h_envrot_256', mb, mats, []), env: windowEnv() };
  await writeSequence('ixs_h_envrot_256', scene, {
    camera: { matrix: lookAt([0, 2.4, 3.2], [0, 0, 0.6]), yfov: 50 * deg }, T: 41, testFrames: [1, 10, 25, 40],
    notes: 'ixs-h: synthetic env (sky 0.0002, a 4x4-texel patch of 100 at 25 deg) rotating 1 deg/frame over a Lambert and a GGX r 0.3 sphere, a floor and a 1.6 m pole',
    frame: (k) => ({ env: { rotationZ: k * deg } }),
  });
});

async function cornellOpenScene(name: string, withRect: boolean, rect?: { matrix: Float32Array; power: number }) {
  const c = await cornellBase();
  const { mb, mats } = cornellWith(c, { open: true, box: true });
  const R = withRect ? [light('rect', rect?.matrix ?? c.rect.matrix, rect?.power ?? c.rect.power, { sizeX: c.rect.sizeX, sizeY: c.rect.sizeY })] : [];
  return { c, R, scene: { ...sceneOf(name, mb, mats, R), env: hdri(OVERCAST, OVERCAST_GAMMA) } as SceneData };
}

def('ixs_i_envradio_256', async () => {
  resetLightIds();
  // the interior rect is the ceiling-height rect of (xiv), facing down (Changelog E-20: the E-13 placement 16 cm from the
  // back wall made the scene heavy-tailed — rung 3.6 needed 2.8–15× its pilot-sized chains — and its M_light:R region
  // lost its only prediction in C-11)
  const { c, R, scene } = await cornellOpenScene('ixs_i_envradio_256', true);
  const L = R[0];
  await writeSequence('ixs_i_envradio_256', scene, {
    camera: cornellCam(c), T: 32, testFrames: [15, 16, 17, 24, 25, 30, 31],
    notes: `ixs-i: open Cornell under ${OVERCAST}: env strength x2 at 16, tint (1, 0.85, 0.7) at 24, interior rect power x2 at 30`,
    frame: (k) => ({
      env: { rotationZ: OVERCAST_GAMMA, strength: k >= 16 ? 2 : 1, tint: k >= 24 ? [1, 0.85, 0.7] : [1, 1, 1] },
      lights: { [L.id]: { matrix: Array.from(L.matrix), power: k >= 30 ? 2 * L.power : L.power } },
    }),
    extra: { lightNames: { R: L.id } },
  });
});

def('ixs_j_envcombo_256', async () => {
  resetLightIds();
  const { c, R, scene } = await cornellOpenScene('ixs_j_envcombo_256', true);
  const L = R[0];
  await writeSequence('ixs_j_envcombo_256', scene, {
    camera: flyCam(0, c.camera.yfov), T: 41, testFrames: [8, 24, 40],
    notes: `ixs-j: open Cornell, ${OVERCAST} rotating 1 deg/frame + the ixs-d fly path + the rect light translating in x`,
    frame: (k) => ({
      camera: flyCam(k, c.camera.yfov), env: { rotationZ: OVERCAST_GAMMA + k * deg },
      lights: { [L.id]: { matrix: rotYMatrix(L.matrix, 0, [lerp(-0.1, 0.1, k / 40), 0.5, -0.02]), power: L.power } },
    }),
  });
});

def('ixs_k_envswap_256', async () => {
  resetLightIds();
  const { c, R, scene } = await cornellOpenScene('ixs_k_envswap_256', true);
  const L = R[0];
  await writeSequence('ixs_k_envswap_256', scene, {
    camera: cornellCam(c), T: 29, testFrames: [19, 20, 21, 28],
    notes: `ixs-k: open Cornell, env map swap at frame 20 (${OVERCAST} -> its 2x box-filtered copy, map id b): history must reset`,
    envMaps: [{ id: 'b', env: halfRes(hdri(OVERCAST, OVERCAST_GAMMA)) }],
    frame: (k) => ({ env: { rotationZ: OVERCAST_GAMMA, ...(k >= 20 ? { map: 'b' } : {}) }, lights: { [L.id]: { matrix: Array.from(L.matrix), power: L.power } } }),
    extra: { resetFrames: [20] },
  });
});

// ---- u8: C0c / C0d / C0e at 256², b = 0 and b = 1 (TD30) ------------------------------------------------------------------------------

const FLOOR = 50;
const floorCam = () => ({ matrix: lookAt([0, 2.2, 2.4], [0, 0, -0.3]), yfov: 50 * deg });
/** b = 1: a diffuse wall at x = 0.9 facing −X, in view, lit by the light (cases (b), (c), (e) at the floor/wall). */
const sideWall = (mb: MeshBuilder, mat: number) => mb.quad([0.9, 0, 1.2], [0.9, 0, -1.8], [0.9, 1.4, -1.8], [0.9, 1.4, 1.2], mat);

function defU8(kind: 'point' | 'spot' | 'rect', mk: () => { lights: LightData[]; camera: { matrix: number[]; yfov: number }; note: string }): void {
  for (const b of [0, 1]) {
    const name = `u8_c0${kind === 'point' ? 'c' : kind === 'spot' ? 'd' : 'e'}_${kind}_b${b}`;
    def(name, async () => {
      resetLightIds();
      const mats = [v1('floor', { diffuse: [0.5, 0.5, 0.5] }), v1('wall', { diffuse: [0.6, 0.6, 0.6] })];
      const mb = new MeshBuilder().floor(-FLOOR, FLOOR, -FLOOR, FLOOR, 0, 0);
      if (b === 1) sideWall(mb, 1);
      const m = mk();
      await writePkg(path.join(OUT_STATIC, name), sceneOf(name, mb, mats, m.lights), {
        camera: m.camera, render: { width: 256, height: 256, maxBounces: b }, lightMode: 'A', flatShaded: true, name,
        source: SRC(`U8 ladder: ${m.note}, b = ${b}${b ? ' + diffuse side wall' : ''}`),
      }, { tier: 'tight' });
    });
  }
}
defU8('point', () => ({ lights: [light('point', new Float32Array(pointM([0.3, 1.0, -0.2])), 60, { color: [1, 0.9, 0.8] })], camera: floorCam(), note: 'C0c point light over a Lambert floor' }));
defU8('spot', () => {
  const tilt = 20 * deg, cc = Math.cos(tilt), s = Math.sin(tilt);
  const m = new Float32Array([cc, s, 0, 0, 0, 0, -1, 0, -s, cc, 0, 0, 0, 1, 0, 1]);   // make-spot-c0d.ts: axis 20° from down toward +X
  return { lights: [light('spot', m, 100, { spotSize: 60 * deg, spotBlend: 0.15 })], camera: { matrix: lookAt([0.45, 2.2, 1.6], [0.45, 0, 0]), yfov: 45 * deg }, note: 'C0d spot (60 deg, blend 0.15, tilted 20 deg)' };
});
defU8('rect', () => {
  const aL = norm([0, -Math.cos(55 * deg), Math.sin(55 * deg)]);
  return { lights: [light('rect', lightToward(aL, [0, 0.5, 0]), 30, { sizeX: 0.6, sizeY: 0.3, color: [0.9, 1, 1] })], camera: floorCam(), note: 'C0e one-sided rect light tilted 55 deg' };
});

// ---- main -------------------------------------------------------------------------------------------------------------------------

export const M5_PACKAGES = (): string[] => gens.map(([n]) => n);
/** Packages written to the env output (validation/out/m5/scenes by default). */
export const M5_ENV_PACKAGES = ['m5s_c0q_openbox_b13', 'm5s_overcast_rect_b3', 'ixs_h_envrot_256', 'ixs_i_envradio_256', 'ixs_j_envcombo_256', 'ixs_k_envswap_256'];

async function main(): Promise<void> {
  const todo = gens.filter(([n]) => !ONLY || ONLY.has(n));
  if (ONLY && todo.length !== ONLY.size) throw new Error(`unknown package(s): ${[...ONLY].filter((n) => !gens.some(([g]) => g === n)).join(', ')}`);
  try {
    for (const [name, g] of todo) {
      await g();
      console.log(`wrote ${path.relative(ROOT, path.join(M5_ENV_PACKAGES.includes(name) ? OUT_ENV : OUT_STATIC, name))}`);
    }
  } finally {
    if (m3cDir) rmSync(m3cDir, { recursive: true, force: true });
  }
}

if (process.argv[1] && import.meta.url === new URL(`file://${path.resolve(process.argv[1])}`).href) {
  main().catch((e) => { console.error(e); process.exit(1); });
}
