#!/usr/bin/env python3
"""extract_luts.py — generate src/core/render/luts/cycles-luts.ts from Cycles' shader.tables (plan §1.5; math.md#bsdf-v2).

  python validation/tools/extract_luts.py [--src shader.tables] [--out src/core/render/luts/cycles-luts.ts]

Without --src the file is downloaded from SOURCE_URL (Blender tag v5.1.2). The script:
  * extracts table_ggx_gen_schlick_ior_s[4096], table_ggx_gen_schlick_s[4096], table_ggx_E[1024], table_ggx_Eavg[32]
    verbatim (decimal literals as written, the 'f' suffix dropped);
  * checks every literal: decimal -> f64 -> f32 (what `new Float32Array([...])` does) equals the correctly rounded
    decimal -> f32 (what the C compiler does for `0.123456f`), so the GPU sees bit-identical floats to Cycles;
  * checks the element counts and the table sums against gap-bsdf §3.5 (to 1e-5);
  * records the source URL, the sha256 of the source file and the sha256 of each table's little-endian f32 bytes.
Stdlib only (no numpy), so it runs with any python3.
"""
from __future__ import annotations

import argparse
import hashlib
import math
import re
import struct
import sys
import urllib.request
from fractions import Fraction
from pathlib import Path

SOURCE_URL = 'https://raw.githubusercontent.com/blender/blender/v5.1.2/intern/cycles/scene/shader.tables'
# (name, count, expected sum from gap-bsdf §3.5 / math.md#bsdf-v2)
TABLES = [
    ('table_ggx_gen_schlick_ior_s', 4096, 184.247126),
    ('table_ggx_gen_schlick_s', 4096, 764.768581),
    ('table_ggx_E', 1024, 849.736018),
    ('table_ggx_Eavg', 32, 25.879163),
]
REPO = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO / 'src/core/render/luts/cycles-luts.ts'


def f32_bits(x: float) -> int:
    return struct.unpack('<I', struct.pack('<f', x))[0]


def bits_f32(b: int) -> float:
    return struct.unpack('<f', struct.pack('<I', b))[0]


def correctly_rounded_f32(lit: str) -> int:
    """Bits of the f32 nearest to the exact decimal value (ties to even)."""
    exact = Fraction(lit)
    cand = f32_bits(float(exact))  # float() is correctly rounded to f64; f32 pack rounds again (maybe double rounding)
    best = None
    for b in (cand - 1, cand, cand + 1):
        if b < 0:
            continue
        v = bits_f32(b)
        if not math.isfinite(v):
            continue
        d = abs(Fraction(v) - exact)
        key = (d, b & 1)  # ties to even mantissa
        if best is None or key < best[0]:
            best = (key, b)
    assert best is not None
    return best[1]


def parse_table(text: str, name: str, count: int) -> list[str]:
    m = re.search(r'static const float ' + re.escape(name) + r'\[(\d+)\]\s*=\s*\{(.*?)\};', text, re.S)
    if not m:
        raise SystemExit(f'{name} not found')
    if int(m.group(1)) != count:
        raise SystemExit(f'{name}: declared size {m.group(1)} != {count}')
    lits = [t.strip() for t in m.group(2).replace('\n', ' ').split(',') if t.strip()]
    lits = [t[:-1] if t.endswith('f') else t for t in lits]
    if len(lits) != count:
        raise SystemExit(f'{name}: {len(lits)} literals != {count}')
    for t in lits:
        if not re.fullmatch(r'-?\d+(\.\d+)?([eE][-+]?\d+)?', t):
            raise SystemExit(f'{name}: unexpected literal {t!r}')
    return lits


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--src', help='local copy of shader.tables (default: download SOURCE_URL)')
    ap.add_argument('--out', default=str(DEFAULT_OUT))
    args = ap.parse_args()

    if args.src:
        raw = Path(args.src).read_bytes()
    else:
        with urllib.request.urlopen(SOURCE_URL, timeout=60) as r:
            raw = r.read()
    src_sha = hashlib.sha256(raw).hexdigest()
    text = raw.decode('utf-8')

    out_lines = [
        '// GENERATED by validation/tools/extract_luts.py — do not edit by hand.',
        '// Cycles precomputed microfacet albedo tables, copied verbatim (plan §1.5; math.md#bsdf-v2; gap-bsdf §3.5).',
        f'// Source: {SOURCE_URL}',
        f'// Source sha256: {src_sha}',
        '// Every literal was checked: decimal -> f64 -> f32 (Float32Array) == correctly rounded decimal -> f32 (C `0.1f`).',
        '// Layout (lookup_table.h): 3D tables data[z*n*n + y*n + x], 2D data[y*n + x]; x = rough, y = mu, z per table.',
        '',
        f"export const LUT_SOURCE_URL = '{SOURCE_URL}';",
        f"export const LUT_SOURCE_SHA256 = '{src_sha}';",
        '',
    ]
    meta = []
    for name, count, want_sum in TABLES:
        lits = parse_table(text, name, count)
        bits = []
        for t in lits:
            via_f64 = f32_bits(float(t))
            exact = correctly_rounded_f32(t)
            if via_f64 != exact:
                raise SystemExit(f'{name}: literal {t} double-rounds differently (f64 path {via_f64:#x} vs {exact:#x})')
            bits.append(exact)
        vals = [bits_f32(b) for b in bits]
        s = math.fsum(vals)
        if abs(s - want_sum) > 1e-5:
            raise SystemExit(f'{name}: sum {s:.6f} != expected {want_sum}')
        tsha = hashlib.sha256(b''.join(struct.pack('<I', b) for b in bits)).hexdigest()
        meta.append((name, count, s, tsha))
        ident = name.upper()
        out_lines.append(f'/** {name}[{count}] (sum {s:.6f}, f32 LE sha256 {tsha}). */')
        out_lines.append(f'export const {ident} = new Float32Array([')
        for i in range(0, count, 16):
            out_lines.append('  ' + ', '.join(lits[i:i + 16]) + ',')
        out_lines.append(']);')
        out_lines.append('')
        print(f'{name}: {count} floats, sum {s:.6f}, sha256(f32) {tsha}')

    out_lines.append('/** Per-table checksums recorded at extraction (tests/material/luts.test.ts re-verifies them). */')
    out_lines.append('export const LUT_CHECKSUMS = {')
    for name, count, s, tsha in meta:
        out_lines.append(f"  {name}: {{ count: {count}, sum: {s:.6f}, sha256F32: '{tsha}' }},")
    out_lines.append('} as const;')
    out_lines.append('')
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(out_lines))
    print(f'wrote {out} (source sha256 {src_sha})')
    return 0


if __name__ == '__main__':
    sys.exit(main())
